name: brew test-bot

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  test-bot:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@f8d4222eb633e65c2a0157383cf80861fc7fae7f # 2026.09.07.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: macos-26-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: macos-26-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - name: Online cask audit
        env:
          TAP_NAME: ${{ steps.set-up-homebrew.outputs.tap-name }}
        run: brew audit --cask --online --strict --tap "$TAP_NAME"

      - name: Install smoke test
        env:
          TAP_NAME: ${{ steps.set-up-homebrew.outputs.tap-name }}
        run: |
          brew install --cask "$TAP_NAME/alttab"
          brew uninstall --cask --zap alttab
